"""
Structured data models for the comparison pipeline (Task 3).

These Pydantic models define the output contract that Task 4 (FastAPI)
will consume. They also validate LLM responses for the career-insight
portion of the pipeline.

Models:
  SkillMatch               — per-skill match result (type, score, what it matched)
  UpskillingRecommendation — one study suggestion from the LLM
  InterviewQuestion        — one interview prep question from the LLM
  LLMInsights              — validated container for all LLM-generated advice
  ComparisonResult         — full Task 3 output combining scores and LLM insights
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Literal, Optional


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  Skill Matching
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

class SkillMatch(BaseModel):
    """Result of matching a single JD skill against the candidate's resume skills.

    Each required and preferred skill from the job description is run
    through the matching layers (exact, alias, ontology-related,
    semantic embedding) and produces one of these records.
    """

    skill: str = Field(
        description="The normalized JD skill being evaluated",
    )
    match_type: Literal["exact", "alias", "related", "semantic", "none"] = Field(
        default="none",
        description=(
            "How the match was found: "
            "exact (identical normalized string), "
            "alias (ontology alias), "
            "related (ontology related-skill, partial credit), "
            "semantic (embedding cosine similarity above threshold), "
            "none (no match found)"
        ),
    )
    score: float = Field(
        default=0.0,
        description=(
            "Confidence score from 0.0 to 1.0. "
            "exact/alias = 1.0, related = 0.75, "
            "semantic >= 0.90 sim = 0.85, >= 0.80 sim = 0.60, "
            "below 0.80 = 0.0"
        ),
    )
    matched_to: Optional[str] = Field(
        default=None,
        description="The resume skill it matched against, None if no match",
    )


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  LLM Response Models
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

class UpskillingRecommendation(BaseModel):
    """A single upskilling recommendation generated by the LLM.

    Each recommendation targets a missing skill and provides a concrete
    resource the candidate can use to close the gap.
    """

    skill: str = Field(
        description="The skill name the candidate should learn",
    )
    reason: str = Field(
        description="Why this skill matters for the target role",
    )
    resource: str = Field(
        description=(
            "A specific learning resource: course name and platform, "
            "book title, or documentation link"
        ),
    )


class InterviewQuestion(BaseModel):
    """A single interview preparation question generated by the LLM.

    Questions are tailored to the specific job description and the
    candidate's identified gaps.
    """

    question: str = Field(
        description="The full interview question text",
    )
    category: Literal["technical", "behavioral", "situational"] = Field(
        description="Question type: technical, behavioral, or situational",
    )


class LLMInsights(BaseModel):
    """Validated container for all LLM-generated career advice.

    This model maps directly to the JSON schema the LLM is prompted
    to return. Pydantic validates the response before it is merged
    into the final ComparisonResult.
    """

    strengths_summary: str = Field(
        default="",
        description=(
            "2-3 sentence explanation of the candidate's strengths "
            "relative to the target role"
        ),
    )
    gaps_summary: str = Field(
        default="",
        description=(
            "2-3 sentence explanation of skill and experience gaps "
            "the candidate should address"
        ),
    )
    upskilling_recommendations: list[UpskillingRecommendation] = Field(
        default_factory=list,
        description="Ordered list of skills to learn, each with a reason and resource",
    )
    interview_questions: list[InterviewQuestion] = Field(
        default_factory=list,
        description="Exactly 5 interview prep questions with category labels",
    )
    salary_insight: str = Field(
        default="",
        description=(
            "1-2 sentence summary relating the posted salary range "
            "to the candidate's experience level"
        ),
    )


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  Final Output — Task 3 → Task 4 Contract
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

class ComparisonResult(BaseModel):
    """Full output of the comparison pipeline (Task 3).

    Combines deterministic scoring (skill match, experience, education)
    with LLM-generated insights (strengths, gaps, recommendations,
    interview questions, salary context). This is the contract that
    Task 4 (FastAPI) will serialize and return to the frontend.
    """

    # ── Scores ─────────────────────────────────────────────────────────
    overall_score: float = Field(
        default=0.0,
        description="Weighted overall match percentage, 0-100",
    )
    skill_score: float = Field(
        default=0.0,
        description="Weighted skill match percentage, 0-100",
    )
    experience_score: Optional[float] = Field(
        default=None,
        description=(
            "Experience match percentage, 0-100. "
            "None when the JD does not specify a years requirement."
        ),
    )
    education_matched: bool = Field(
        default=False,
        description="Whether any JD education requirement was found in the resume",
    )

    # ── Per-skill match details ────────────────────────────────────────
    required_skill_matches: list[SkillMatch] = Field(
        default_factory=list,
        description="Match result for each required skill from the JD",
    )
    preferred_skill_matches: list[SkillMatch] = Field(
        default_factory=list,
        description="Match result for each preferred skill from the JD",
    )
    missing_required_skills: list[str] = Field(
        default_factory=list,
        description="Required skills where score == 0.0 (no match found)",
    )
    missing_preferred_skills: list[str] = Field(
        default_factory=list,
        description="Preferred skills where score == 0.0 (no match found)",
    )

    # ── LLM-generated insights ─────────────────────────────────────────
    strengths_summary: str = Field(
        default="",
        description="LLM-generated summary of candidate strengths",
    )
    gaps_summary: str = Field(
        default="",
        description="LLM-generated summary of skill and experience gaps",
    )
    upskilling_recommendations: list[UpskillingRecommendation] = Field(
        default_factory=list,
        description="LLM-generated study recommendations for missing skills",
    )
    interview_questions: list[InterviewQuestion] = Field(
        default_factory=list,
        description="LLM-generated interview preparation questions",
    )
    salary_insight: str = Field(
        default="",
        description="LLM-generated salary context for the candidate",
    )

    # ── Metadata ───────────────────────────────────────────────────────
    errors: list[str] = Field(
        default_factory=list,
        description=(
            "Non-fatal issues encountered during comparison. "
            "Partial results are still usable when errors are present."
        ),
    )
